POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "e7d3ae24-560a-4a77-9660-3bb5bbf927b6"    
}


###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "e2afa43c-de24-4d83-b5a5-581a1d740d4c"    
}


