POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_to": "3e44573d-7b58-420f-ae1f-a90270e1af95",
    "account_id_from": "35db8790-39fa-46ea-a8a9-422796a2b29c",
    "amount": 7
}


