POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_to": "5cae996b-2428-47c4-a973-60b21fa75fec",
    "account_id_from": "49ae97cb-0a47-47e8-96b6-284e6f914736",
    "amount": 5
}


